// These names are taken from PvZ Emulator.
export enum ZombieType {
    zombie = 0x0,
    flag = 0x1,
    conehead = 0x2,
    poleVaulting = 0x3,
    buckethead = 0x4,
    newspaper = 0x5,
    screendoor = 0x6,
    football = 0x7,
    dancing = 0x8,
    backupDancer = 0x9,
    duckyTube = 0xa,
    snorkel = 0xb,
    zomboni = 0xc,
    dolphinRider = 0xe,
    jackInTheBox = 0xf,
    balloon = 0x10,
    digger = 0x11,
    pogo = 0x12,
    yeti = 0x13,
    bungee = 0x14,
    ladder = 0x15,
    catapult = 0x16,
    gargantuar = 0x17,
    imp = 0x18,
    gigaGargantuar = 0x20,
};

export const zombieTypeAbbrToEnum: { [key: string]: ZombieType } = {
    "base": ZombieType.zombie,  // taken from English PvZ Wiki referring to it as "the most basic zombie"
                                // to avoid clash with zomboni
    "flag": ZombieType.flag,
    "cone": ZombieType.conehead,
    "pole": ZombieType.poleVaulting,
    "buck": ZombieType.buckethead,
    "news": ZombieType.newspaper,
    "scre": ZombieType.screendoor,
    "foot": ZombieType.football,
    "danc": ZombieType.dancing,
    "back": ZombieType.backupDancer,
    "duck": ZombieType.duckyTube,
    "snor": ZombieType.snorkel,
    "zomb": ZombieType.zomboni,
    "dolp": ZombieType.dolphinRider,
    "jack": ZombieType.jackInTheBox,
    "ball": ZombieType.balloon,
    "digg": ZombieType.digger,
    "pogo": ZombieType.pogo,
    "yeti": ZombieType.yeti,
    "bung": ZombieType.bungee,
    "ladd": ZombieType.ladder,
    "cata": ZombieType.catapult,
    "garg": ZombieType.gargantuar,
    "imp": ZombieType.imp,
    "giga": ZombieType.gigaGargantuar,
};
