// These names are taken from PvZ Emulator.
export enum ZombieType {
    zombie = 0x0,
    flag = 0x1,
    conehead = 0x2,
    poleVaulting = 0x3,
    buckethead = 0x4,
    newspaper = 0x5,
    screendoor = 0x6,
    football = 0x7,
    dancing = 0x8,
    backupDancer = 0x9,
    duckyTube = 0xa,
    snorkel = 0xb,
    zomboni = 0xc,
    dolphinRider = 0xe,
    jackInTheBox = 0xf,
    balloon = 0x10,
    digger = 0x11,
    pogo = 0x12,
    yeti = 0x13,
    bungee = 0x14,
    ladder = 0x15,
    catapult = 0x16,
    gargantuar = 0x17,
    imp = 0x18,
    gigaGargantuar = 0x20,
};

export const acceptableZombieTypes: ZombieType[] = [ZombieType.poleVaulting, ZombieType.buckethead, ZombieType.screendoor, ZombieType.football, ZombieType.dancing, ZombieType.snorkel, ZombieType.zomboni, ZombieType.dolphinRider, ZombieType.jackInTheBox, ZombieType.balloon, ZombieType.digger, ZombieType.pogo, ZombieType.bungee, ZombieType.ladder, ZombieType.catapult, ZombieType.gargantuar, ZombieType.gigaGargantuar];

export const zombieTypeCNAbbrToEnum: { [key: string]: ZombieType } = {
    "普": ZombieType.zombie,
    "旗": ZombieType.flag,
    "障": ZombieType.conehead,
    "杆": ZombieType.poleVaulting,
    "桶": ZombieType.buckethead,
    "报": ZombieType.buckethead,
    "门": ZombieType.screendoor,
    "橄": ZombieType.football,
    "舞": ZombieType.dancing,
    "伴": ZombieType.backupDancer,
    "鸭": ZombieType.duckyTube,
    "潜": ZombieType.snorkel,
    "车": ZombieType.zomboni,
    "豚": ZombieType.dolphinRider,
    "丑": ZombieType.jackInTheBox,
    "气": ZombieType.balloon,
    "矿": ZombieType.digger,
    "跳": ZombieType.pogo,
    "雪": ZombieType.yeti,
    "偷": ZombieType.bungee,
    "梯": ZombieType.ladder,
    "篮": ZombieType.catapult,
    "白": ZombieType.gargantuar,
    "鬼": ZombieType.imp,
    "红": ZombieType.gigaGargantuar,
};

export const zombieTypeENAbbrToEnum: { [key: string]: ZombieType } = {
    "regu": ZombieType.zombie,
    "flag": ZombieType.flag,
    "cone": ZombieType.conehead,
    "pole": ZombieType.poleVaulting,
    "buck": ZombieType.buckethead,
    "news": ZombieType.buckethead,
    "scre": ZombieType.screendoor,
    "foot": ZombieType.football,
    "danc": ZombieType.dancing,
    "back": ZombieType.backupDancer,
    "duck": ZombieType.duckyTube,
    "snor": ZombieType.snorkel,
    "zomb": ZombieType.zomboni,
    "dolp": ZombieType.dolphinRider,
    "jack": ZombieType.jackInTheBox,
    "ball": ZombieType.balloon,
    "digg": ZombieType.digger,
    "pogo": ZombieType.pogo,
    "yeti": ZombieType.yeti,
    "bung": ZombieType.bungee,
    "ladd": ZombieType.ladder,
    "cata": ZombieType.catapult,
    "garg": ZombieType.gargantuar,
    "imp": ZombieType.imp,
    "giga": ZombieType.gigaGargantuar,
};



/* eslint-disable @typescript-eslint/naming-convention */
export const bannedZombieTypes: { [key: string]: ZombieType[] } = {
    "DE": [ZombieType.snorkel, ZombieType.dolphinRider],
    "NE": [ZombieType.snorkel, ZombieType.zomboni, ZombieType.dolphinRider],
    "PE": [],
    "FE": [],
    "RE": [ZombieType.dancing, ZombieType.snorkel, ZombieType.dolphinRider,
    ZombieType.digger],
    "ME": [ZombieType.dancing, ZombieType.snorkel, ZombieType.dolphinRider,
    ZombieType.digger]
};